### ISSUE TITLE
Backend Express Server

### ISSUE THREAD

**Issue by AhadKhan98** [Berea-CS-Courses/capstone-project-AhadKhan98#15]
__Allows the backend to perform CRUD operations to retrieve/update data in MongoDB__
- [x] Implement user signup flow using the backend api to create new user objects in MongoDB. Complete by Monday.
- [x] Implement user login flow using the backend api to log existing users in. Complete by Monday.
- [x] Create a table in MongoDB and add functionality for storing pending matches. Complete by Tuesday.
- [x] Create the helper profile page in the frontend. Complete by Tuesday.
- [x] Facilitate data required by the helper profile page from the database. Complete by Wednesday.
- [x] Change all React components to query data from the API rather than being hardcoded. Complete by Friday.

__I would like feedback on ...__ 
_Whether all potential cases are being covered in the backend_

**Comment by mario-nakazawa** [comment]
Looks good to me. One thing I ask is that you include comments in your code that it would be easier to follow.

**Comment by AhadKhan98** [comment]
> thing I ask is that you i

Will do! Thanks.
