### ISSUE TITLE
Deliverable #2

### ISSUE THREAD

**Issue by AhadKhan98** [Berea-CS-Courses/capstone-project-AhadKhan98#5]
This document contains a detailed breakdown of my project idea. The idea is broken down into components which are then further broken down into sub-components.

__I would like feedback on ...__ 
_Section # 2: Do the workings of each component make sense?_
_Section # 3: Do you that that the prioritization list would work out?_

**Comment by smanalai** [comment]
This is a great breakdown of the major components of your application. I can also see a clear hierarchy of the main components for a working app. To address request feedback, here is the answer to two of your questions.  1) Yes, the workings of each component are explained very well. You did a great job of going into detail and talking about why each component was necessary, how exactly you would implement it and which tools you would use. 2) I think your prioritization list would work fine. In my personal experience, I usually focus on the front-end, backend, and then link the backend to the front-end and a database to store the user information. However, I think working on the front-end, creating a database, and then working on the backend should work just fine as well. Overall, I think you have a good sense of what you need to do. Keep up the good work.
