### ISSUE TITLE
Deliverable # 3 - Draft

### ISSUE THREAD

**Issue by AhadKhan98** [Berea-CS-Courses/capstone-project-AhadKhan98#7]
_My vision for the LoFi Prototype is to have a UI sketch of every single component that will be shown in the frontend. Additionally, I will have a User Task Flow Diagram for the system model diagram._

Accomplishments:
1. UI Sketches of every single component

To-Do:
1. User Task Flow Diagram

**Comment by jazzij** [comment]
The sketch is very clear. It's worth thinking about ways to make the design of the system more efficient for the two types of users engaged. Looking forward to detailed wireframes or a paper prototype to see more how the system interaction works!

**Comment by jazzij** [comment]
The user flow diagram looks pretty good, but it's missing the step about how a user chooses which chat server to join. Is there a screen with a list? Do they need to have a code, like zoom? Do they have to be invited?
