### ISSUE TITLE
[Deliverable # 3]

### ISSUE THREAD

**Issue by AhadKhan98** [Berea-CS-Courses/capstone-project-AhadKhan98#8]
My vision for the LoFi Prototype is to have a UI sketch of every single component that will be shown in the frontend. Additionally, I will have a User Task Flow Diagram for the system model diagram.

Accomplishments:

UI Sketches of every single component
User Flow Diagram for 3 major components

**Comment by jazzij** [comment]
I think your diagrams give a very clear picture of your intended design and flow. For the next step, I would like to see more detail about your rationale for designing these features this way. Some of the flows and features seem arbitrary, and could end up creating a negative user experience. In addition, you mentioned that your wanted your app to feature payment via a coin system (like Reddit I suppose?). How would coins be earned, stored, and spent throughout this flow?

**Comment by smanalai** [comment]
You have created a great initial UI sketch of your application it shows the different components of your application clearly. Your user flow diagram is also clear and identifies the various components and how users would interact with your system. Your D3 document is missing the reflection section of the assignment but overall, I think you did a good job of creating your prototype and I think this process will help with the implementation of the system you have prototyped.

**Comment by AhadKhan98** [comment]
> You have created a great initial UI sketch of your application it shows the different components of your application clearly. Your user flow diagram is also clear and identifies the various components and how users would interact with your system. Your D3 document is missing the reflection section of the assignment but overall, I think you did a good job of creating your prototype and I think this process will help with the implementation of the system you have prototyped.

You are right! I completely overlooked the reflection section. I'll add it right away.
